
package co.edu.unicesar.interfaz;


import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import co.edu.unicesar.modelo.ListaPublicacion;

public class ConsultarDatos extends javax.swing.JPanel {

    private ListaPublicacion modelo;
    DefaultTableModel tabla;
    private String titu[] = {"ISBN", "TITULO", "AUTOR", "TIPO", "ANIO", "COSTO", "No PAG", "EDICION", "FORMATO", "DURACION", "PESO"};
    private String datos[][] = {null};
    
    public ConsultarDatos() {
        initComponents();
        
        this.modelo = new ListaPublicacion();
        tabla = new DefaultTableModel();
        for (int i=0; i<titu.length; i++)
        {
            tabla.addColumn(titu[i]);
        }
        tabla1.setModel(tabla);
        
    }
    
    public void datosText() {
        BufferedReader bufferedReader = null;

        try {
            
            bufferedReader = new BufferedReader(new FileReader("datos.txt"));
            String line = bufferedReader.readLine();

            while (line != null) {
                String[] rowfields = line.split(";");
                tabla.addRow(rowfields);
                line = bufferedReader.readLine();
            }

        } catch (IOException x) {
            JOptionPane.showMessageDialog(null, "error");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        eliminarlista = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSULTAR PUBLICACION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 450, 43));

        buscar.setBackground(new java.awt.Color(204, 255, 204));
        buscar.setForeground(new java.awt.Color(0, 0, 0));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 445, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ISBN PUBLICACION");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 150, -1));

        eliminarlista.setBackground(new java.awt.Color(204, 255, 204));
        eliminarlista.setForeground(new java.awt.Color(51, 255, 51));
        eliminarlista.setText("ELIMINAR PUBLICACION");
        eliminarlista.setBorder(null);
        eliminarlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarlistaActionPerformed(evt);
            }
        });
        add(eliminarlista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, 57));

        atras.setBackground(new java.awt.Color(255, 0, 0));
        atras.setForeground(new java.awt.Color(102, 0, 51));
        atras.setText("ATRAS");
        atras.setBorder(null);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 124, 57));

        tabla1.setBackground(new java.awt.Color(204, 255, 204));
        tabla1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tabla1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        tabla1 = new javax.swing.JTable()
        {
            public boolean isCellEditable (int rowIndex, int colIndex)
            return false;
        }
        tabla1.setForeground(new java.awt.Color(0, 0, 0));
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "TITULO", "AUTOR", "TIPO", "COSTO", "N°PAGINAS", "N°EDICION", "PESO", "FORMATO", "DURACION"
            }
        ));
        tabla1.setGridColor(new java.awt.Color(204, 255, 204));
        tabla1.setName("idbn,titulo,autor,año pub,costo,n°paginas,n°edicion,formato,peso,duracion"); // NOI18N
        tabla1.setRowHeight(22);
        tabla1.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tabla1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 840, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String dato = buscar.getText();
        
        for (int i=0; i<tabla1.getRowCount(); i++)
        {
            if (tabla1.getValueAt(i, 0).equals(dato))
            {
                tabla1.changeSelection(i, 0, false, false);
            }
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
      
     MenuPrincipal.fondo.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void eliminarlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarlistaActionPerformed
        int fila = tabla1.getSelectedRow();
        tabla.removeRow(fila);
    }//GEN-LAST:event_eliminarlistaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JTextField buscar;
    private javax.swing.JButton eliminarlista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
