/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.unicesar.interfazAgregar;

/**
 *
 * @author DAVID
 */
public class Registrar extends javax.swing.JPanel {

    /**
     * Creates new form Agregar
     */
    public Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Tipo = new javax.swing.JComboBox<>();
        textautor = new javax.swing.JTextField();
        textaño = new javax.swing.JTextField();
        textprecio = new javax.swing.JTextField();
        textisbn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        textnpaginas = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        textnpaginas1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGREGAR PUBLICACION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 310, -1));

        textitulo.setBackground(new java.awt.Color(204, 255, 255));
        textitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textituloActionPerformed(evt);
            }
        });
        add(textitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 100, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ISBN :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Titulo:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Autor:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Año:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Tipo", "Libro", "AudioLibro", "" }));
        Tipo.setToolTipText("");
        Tipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });
        add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 130, 30));

        textautor.setBackground(new java.awt.Color(204, 255, 255));
        textautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textautorActionPerformed(evt);
            }
        });
        add(textautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, 30));

        textaño.setBackground(new java.awt.Color(204, 255, 255));
        textaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textañoActionPerformed(evt);
            }
        });
        add(textaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 100, 30));

        textprecio.setBackground(new java.awt.Color(204, 255, 255));
        textprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textprecioActionPerformed(evt);
            }
        });
        add(textprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 100, 30));

        textisbn.setBackground(new java.awt.Color(204, 255, 255));
        textisbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textisbnActionPerformed(evt);
            }
        });
        add(textisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 100, 30));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator1.setAlignmentX(4.0F);
        jSeparator1.setAlignmentY(4.0F);
        jSeparator1.setMaximumSize(new java.awt.Dimension(50000, 50000));
        jSeparator1.setMinimumSize(new java.awt.Dimension(100, 100));
        jSeparator1.setPreferredSize(new java.awt.Dimension(80, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 690, 10));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Edicion");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 100, 30));

        textnpaginas.setBackground(new java.awt.Color(204, 255, 255));
        add(textnpaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 120, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator2.setAlignmentX(4.0F);
        jSeparator2.setAlignmentY(4.0F);
        jSeparator2.setMaximumSize(new java.awt.Dimension(50000, 50000));
        jSeparator2.setMinimumSize(new java.awt.Dimension(100, 100));
        jSeparator2.setPreferredSize(new java.awt.Dimension(80, 50));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 690, 10));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 120, 50));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 120, 50));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator3.setAlignmentX(4.0F);
        jSeparator3.setAlignmentY(4.0F);
        jSeparator3.setMaximumSize(new java.awt.Dimension(50000, 50000));
        jSeparator3.setMinimumSize(new java.awt.Dimension(100, 100));
        jSeparator3.setPreferredSize(new java.awt.Dimension(80, 50));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 690, 10));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("N° Paginas");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 100, 30));

        textnpaginas1.setBackground(new java.awt.Color(204, 255, 255));
        add(textnpaginas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void textituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textituloActionPerformed

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed

    private void textautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textautorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textautorActionPerformed

    private void textañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textañoActionPerformed

    private void textprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textprecioActionPerformed

    private void textisbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textisbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textisbnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField textautor;
    private javax.swing.JTextField textaño;
    private javax.swing.JTextField textisbn;
    private javax.swing.JTextField textitulo;
    private javax.swing.JTextField textnpaginas;
    private javax.swing.JTextField textnpaginas1;
    private javax.swing.JTextField textprecio;
    // End of variables declaration//GEN-END:variables
}
